config/routes.rb
Rails.application.routes.draw do
  devise_for :users

 root 'welcome#index'

resources :users

resources :bloggs

get '/sports', to: 'bloggs#index'
post '/sportscreate', to: 'bloggs#create'
get '/sportsnew', to: 'bloggs#new'
get '/sportsedit', to: 'bloggs#edit'
get '/sportsshow', to: 'bloggs#show'
put '/sportsupdate', to: 'bloggs#update'
delete '/sportsdelete', to: 'bloggs#destroy'

get '/music',  to: 'bloggs#index'
post '/musiccreate', to: 'bloggs#create'
get '/musicnew', to: 'bloggs#new'
get '/musicedit', to: 'bloggs#edit'
get '/musicshow', to: 'bloggs#show'
put '/musicupdate', to: 'bloggs#update'
delete '/musicdelete', to: 'bloggs#destroy'

end

app/models/blogg.rb
class Blogg < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :large => "100x100>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
  def check_privileges!
    redirect_to "/", notice: "You dont have enough privileges to be here" unless current_user
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up){|u|u.permit(:email, :password, :password_confirmation, :avatar)}
    # devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/bloggs_controller.rb
class BloggsController < ApplicationController

	before_filter :check_privileges!, only: [:new, :create, :edit, :update, :destroy]
	def index
		
		path = request.original_url
		blog_type = path.split('/').last 
		if user_signed_in?
			@blogs=Blogg.where(user_id: current_user.id, blog_type: blog_type)
		else
			@blogs=Blogg.all
		end
	end
	
	def new
		@blogs=Blogg.new
	end
	def create
		@blogs=Blogg.new(blog_params)
		@blogs.user_id=current_user.id
		respond_to do |format|
			if @blogs.save
				
				format.html {redirect_to bloggs_path, notice: 'Your post has been sent for approval'}
			else
				format.html {redirect_to bloggs_path, notice: 'something went wrong'}
			end
		end
	end
	def show
		@blogs = Blogg.find(params[:id])
	end
	def edit
		@blogs = Blogg.find(params[:id])
	end
	def update		
		@blogs = Blogg.find(params[:id])
		if @blogs.update(params[:blogg].permit(:name, :content, :blog_type))
			redirect_to bloggs_path, :notice => "Your blogs was updated"
		else
			render "edit"
		end
	end
	def destroy
		@blogs = Blogg.find(params[:id])
		@blogs.destroy
		redirect_to bloggs_path, :notice => "Your blogs was deleted"
	end

	private
	def blog_params
		params.require(:blogg).permit(:name, :content, :blog_type)
	end

end

app/controllers/entertainment_controller.rb
class EntertainmentController < ApplicationController
end

app/controllers/life_productivity_controller.rb
class LifeProductivityController < ApplicationController
def index
end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
	before_filter :check_privileges!, only: [:new, :create, :edit, :update, :destroy]
	def index
		if user_signed_in?
			
			@music=Sport.where(user_id: current_user.id, blog_type: 'music')
		else
			@music=Sport.where(blog_type: 'music')
		end
	end
	
	def new
		@music=Sport.new
	end
	def create
		
		@music=Sport.new(params[:sport ].permit(:name, :content, :blog_type))
		@music.user_id=current_user.id
		respond_to do |format|
			if @music.save
				binding.pry
				
				format.html {redirect_to music_index_path, notice: 'Your post has been sent for approval'}
			else
				format.html {redirect_to music_index_path, notice: 'something went wrong'}
			end
		end
	end
	def show
		@music = Sport.find(params[:id])
	end
	def edit
		binding.pry
		@music = Sport.find(params[:id])
	end
	def update
		binding.pry
		@music = Sport.find(params[:id])
		if @music.update(params[:sport].permit(:name, :content, :blog_type))
			redirect_to music_index_path, :notice => "Your sports was updated"
		else
			render "edit"
		end
	end
	def destroy
		@music = Sport.find(params[:id])
		@music.destroy
		redirect_to music_index_path, :notice => "Your sports was deleted"
	end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
	before_filter :check_privileges!, only: [:new, :create, :edit, :update, :destroy]
	def index
		if user_signed_in?
			
			@sports=Sport.where(user_id: current_user.id, blog_type: 'sports')
		else
			@sports=Sport.where(blog_type: 'sports')
		end
	end
	
	def new
		@sports=Sport.new
	end
	def create
		@sports=Sport.new(params[:sport ].permit(:name, :content, :blog_type))
		@sports.user_id=current_user.id
		respond_to do |format|
			if @sports.save
				
				format.html {redirect_to sports_path, notice: 'Your post has been sent for approval'}
			else
				format.html {redirect_to sports_path, notice: 'something went wrong'}
			end
		end
	end
	def show
		@sports = Sport.find(params[:id])
	end
	def edit
		@sports = Sport.find(params[:id])
	end
	def update
		binding.pry
		
		@sports = Sport.find(params[:id])
		if @sports.update(params[:sport].permit(:name, :content, :blog_type))
			redirect_to sports_path, :notice => "Your sports was updated"
		else
			render "edit"
		end
	end
	def destroy
		@sports = Sport.find(params[:id])
		@sports.destroy
		redirect_to sports_path, :notice => "Your sports was deleted"
	end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
 	@user= User.find(params[:id])
  end
  def new
    @user= User.new
  end
  def create
  	binding.pry
    @user = User.create( user_params )
  end
end
private 
def user_params
  params.require(:user).permit(:avatar)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
	@blogs = Blogg.first(2)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/entertainment_helper.rb
module EntertainmentHelper
end

app/helpers/life_productivity_helper.rb
module LifeProductivityHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/user/registration_helper.rb
module User::RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bloggs/_form.html.erb
<%= form_for(@sports) do |f| %>
  <% if @sports.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @sports.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bloggs/edit.html.erb
<h1>Edit Sports blog</h1>
<%=form_for @blogs do |f| %>
<%if @blogs.errors.any? %>
<h2>Errors:</h2>
<ul>
<%@blogs.errors.full_messages.each do |m| %>
<li><%= m %></li>
<%end%>
</ul>
<%end%>
<p>
<%=f.label :name %><br/>
<%=f.text_field :name %>
</p>
<p>
<%=f.label :content %><br/>
<%=f.text_area :content %>
</p>
<p>
<%=f.submit "Update blog" %>
</p>
<%end%>

app/views/bloggs/index.html.erb
<script type="text/javascript" charset="utf-8">
	$(function() {
 		var path=window.location.pathname
   	if(path=='/sportsnew'){
     	var pathname = 'sportsnew'
   	}else{
     	var pathname='musicnew'
 	  }
  	var elem = document.getElementById("new_path");
  	elem.value=pathname
   	window.alert(elem.value)
	})
</script>
	<div id='head'>Welcome to blogs section</div>

	  <div id = "index">

	
	    <% @blogs.each do |blog| %>
		    <p><%=link_to blog.name, sports_path %> </h4></p>
			<p><%=truncate blog.content, length: 160  %> <%= link_to 'read more', blogg_path(blog) %> </p>

			<% if user_signed_in? %>      
		        
		        <%= link_to 'Edit', sportsedit_path(blog) %>
		        <%= link_to 'Destroy', sportsdelete_path, method: :delete, data: { confirm: 'Are you sure?' } %>
		    <%end%> 
	    <% end %>
	  </div>

<br>
<div id='new_path'>
	<% if user_signed_in? %>
		<%= link_to 'New Blog', sportsnew_path %>
	<%end%>
</div>

app/views/bloggs/new.html.erb
<script type="text/javascript" charset="utf-8">
      $(function() {
        var blog_type=window.location.pathname
        if(blog_type=='/sportsnew'){
        	var type = 'sports'
        }else{
        	var type='music'
        }
        var elem = document.getElementById("blogg_blog_type");
        elem.value=type
      })
    </script>
<h1>Add a new blog </h1>
<%= form_for @blogs do |f| %>
<%if @blogs.errors.any? %>
<h2>Errors:</h2>
<ul>
<%@blogs.errors.full_messages.each do |m| %>
<li><%= m %></li>
<%end%>
</ul>
<%end%>
<p><%= f.label :name %><br/>
<%= f.text_field :name %>
</p>
<p><%= f.label :content %><br/>
<%= f.text_area :content %>
</p>

<p><%= f.label :blog_type %><br/>
<%= f.text_area :blog_type %>
</p>

<p><%= f.submit "Add a new blog" %>
</p>
<%end%>

app/views/bloggs/show.html.erb
<!DOCTYPE html>
<html>
  <div id = "index">
    
      <h1><%=@blogs.name %></h1>
      <p><%= @blogs.content %></p>
      <small>blogs bloged <%= time_ago_in_words(@blogs.created_at) %> ago <br/> </small>
      
      <br />
      <%= link_to 'Back to blogs', bloggs_path %> 
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_blogg_path(@blogs[:id]) %>
        <%= link_to 'Destroy', @blogs, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
   
  </div>
</html>

app/views/entertainment/index.html.erb
<div id='head'>Welcome To Entertainment</div>

app/views/life_productivity/index.html.erb
<div id='head'>Welcome to Life Productivity</id>

app/views/life_productivity/life_productivity.html.erb
<div id='head'>Welcome to Life Productivity</id>

app/views/music/edit.html.erb
<h1>Edit music blog</h1>
<%=form_for @music do |f| %>
<%if @music.errors.any? %>
<h2>Errors:</h2>
<ul>
<%@music.errors.full_messages.each do |m| %>
<li><%= m %></li>
<%end%>
</ul>
<%end%>
<p>
<%=f.label :name %><br/>
<%=f.text_field :name %>
</p>
<p>
<%=f.label :content %><br/>
<%=f.text_area :content %>
</p>
<p>
<%=f.submit "Update blog" %>
</p>
<%end%>

app/views/music/index.html.erb
<div id='head'>Welcome to Music section</div>

  <div id = "index">
    <% @music.each do |music| %>
	    <p><%=link_to music.name, music %> </h4></p>
		<p><%=truncate music.content, length: 160  %> <%= link_to 'read more', music_path(music) %> </p>

		<% if user_signed_in? %>      
	        
	        <%= link_to 'Edit', edit_music_path(music) %>
	        <%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %>
	    <%end%> 
    <% end %>
  </div>

<br>
<% if user_signed_in? %>
	<%= link_to 'New Blog', new_music_path %>
<%end%>

app/views/music/new.html.erb
<h1>Add a new blog </h1>
<%= form_for @music do |m| %>
<%if @music.errors.any? %>
<h2>Errors:</h2>
<ul>
<%@music.errors.full_messages.each do |f| %>
<li><%= m %></li>
<%end%>
</ul>
<%end%>
<p><%= m.label :name %><br/>
<%= m.text_field :name %>
</p>
<p><%= m.label :content %><br/>
<%= m.text_area :content %>
</p>
<p><%= m.label :blog_type %><br/>
<%= m.text_area :blog_type %>
</p>
<p><%= m.submit "Add a new blog" %>
<%binding.pry%>
</p>
<%end%>

app/views/music/show.html.erb
<!DOCTYPE html>
<html>
  <div id = "index">
    
      <h1><%=@music.name %></h1>
      <p><%= @music.content %></p>
      <small>music bloged <%= time_ago_in_words(@music.created_at) %> ago <br/> </small>
      
      <br />
      <%= link_to 'Back to music',  music_index_path %> 
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_music_path(@music[:id]) %>
        <%= link_to 'Destroy', @music, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
   
  </div>
</html>

app/views/sports/edit.html.erb
<h1>Edit Sports blog</h1>
<%=form_for @sports do |f| %>
<%if @sports.errors.any? %>
<h2>Errors:</h2>
<ul>
<%@sports.errors.full_messages.each do |m| %>
<li><%= m %></li>
<%end%>
</ul>
<%end%>
<p>
<%=f.label :name %><br/>
<%=f.text_field :name %>
</p>
<p>
<%=f.label :content %><br/>
<%=f.text_area :content %>
</p>
<p>
<%=f.submit "Update blog" %>
</p>
<%end%>

app/views/sports/index.html.erb
<div id='head'>Welcome to Sports section</div>

  <div id = "index">
    <% @sports.each do |sports| %>
	    <p><%=link_to sports.name, sports %> </h4></p>
		<p><%=truncate sports.content, length: 160  %> <%= link_to 'read more', sport_path(sports) %> </p>

		<% if user_signed_in? %>      
	        
	        <%= link_to 'Edit', edit_sport_path(sports) %>
	        <%= link_to 'Destroy', sports, method: :delete, data: { confirm: 'Are you sure?' } %>
	    <%end%> 
    <% end %>
  </div>

<br>
<% if user_signed_in? %>
	<%= link_to 'New Blog', new_sport_path %>
<%end%>

app/views/sports/new.html.erb
<h1>Add a new blog </h1>
<%= form_for @sports do |f| %>
<%if @sports.errors.any? %>
<h2>Errors:</h2>
<ul>
<%@sports.errors.full_messages.each do |m| %>
<li><%= m %></li>
<%end%>
</ul>
<%end%>
<p><%= f.label :name %><br/>
<%= f.text_field :name %>
</p>
<p><%= f.label :content %><br/>
<%= f.text_area :content %>
</p>
<p><%= f.label :blog_type %><br/>
<%= f.text_area :blog_type %>
</p>
<p><%= f.submit "Add a new blog" %>
</p>
<%end%>

app/views/sports/show.html.erb
<!DOCTYPE html>
<html>
  <div id = "index">
    
      <h1><%=@sports.name %></h1>
      <p><%= @sports.content %></p>
      <small>sports bloged <%= time_ago_in_words(@sports.created_at) %> ago <br/> </small>
      
      <br />
      <%= link_to 'Back to sports', sports_path %> 
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_sport_path(@sports[:id]) %>
        <%= link_to 'Destroy', @sports, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
   
  </div>
</html>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div id='box'>
<table>
    

<tr>   
  <% @blogs.collect{ |p| {name: p.name, content: p.content }}.each do |pr| %>
    <th width="25px"><%= pr[:name] %></th>
    <th width="25px"><%= truncate pr[:content], length: 160  %> </th>
  <% end %>
</tr>
</table>	
</div>